package com.strabled.composepreferencessample

val preferences = mapOf<String, Any>(
    "sw1" to false,
    "sw2" to true,
    "sw3" to false,
    "sw4" to true,
    "cb1" to false,
    "cb2" to true,
    "cb3" to true,
    "cb4" to false,
    "sl1" to 0.5f,
    "sl2" to 3,
    "sl3" to 5.6,
    "sl4" to 4L,
    "et1" to "Some text",
    "et2" to "Some other text",
    "et3" to "",
    "et4" to "",
    "et5" to "",
    "et6" to "",
    "dl1" to "item1",
    "dl2" to "item2",
    "dl3" to "item3",
    "ddl1" to "item1",
    "ddl2" to "item2",
    "ddl3" to "item3",
    "bl1" to "item1",
    "bl2" to "item2",
    "bl3" to "item3",
    "bl4" to "item4",
    "msl1" to setOf("10", "20", "30"),
    "msl2" to setOf("item2", "item3"),
    "msl3" to setOf<String>(),
    "cp1" to 0xFFF00000.toInt(),
    "cp2" to 0xFF12AFDE,
    "cp3" to 0xFF000000.toInt()
)